run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - revive

linters-settings:
  goimports:
    local-prefixes: app
  
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
      - name: comment-spacings
      - name: indent-error-flow
      - name: package-comments 

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0